/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 record_room.glb --transform
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useThree } from '@react-three/fiber'
import { scroll_animation_1, scroll_animation_2 } from '../../utils/scroll_animations'

export function Room(props) {

  const { nodes, materials } = useGLTF('/models/record_room-transformed.glb')
  const room = useRef()
  const chair = useRef()
  const camera = useThree((state) => state.camera)
  const tl = gsap.timeline()

  useLayoutEffect(() => {
    // console.log(camera)

    // About section animation
    scroll_animation_1(tl, room, camera, chair)
    scroll_animation_2(tl, room, camera,chair)
  }, [])

  return (
    <group {...props} dispose={null} ref={room}>
      <group name="Scene">
        <group name="coffee_table" position={[-1.05, 0.83, 0.81]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59}>
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Material.007']} castShadow receiveShadow/>
          <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={materials['Material.027']} castShadow receiveShadow/>
        </group>
        <group name="mic" position={[0.77, 0.57, -1.42]} rotation={[Math.PI, -1.11, Math.PI]} scale={0.59}>
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane029_1" geometry={nodes.Plane029_1.geometry} material={materials['Material.025']} castShadow receiveShadow/>
          <mesh name="Plane029_2" geometry={nodes.Plane029_2.geometry} material={materials['Material.026']} castShadow receiveShadow/>
        </group>
        <group name="chair" position={[1.24, 0.77, 0.34]}  rotation={[0, 1.52, 0]} scale={0.59} ref={chair}>
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.025']} castShadow receiveShadow/>
          <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials['Material.029']} castShadow receiveShadow/>
        </group>
        <mesh name="z_flag" geometry={nodes.z_flag.geometry} material={materials['Material.035']} position={[1.46, 2.44, -1.75]} rotation={[0, Math.PI / 4, Math.PI / 2]} scale={[0.61, 0.78, 0.41]} castShadow receiveShadow/>
        <mesh name="rug" geometry={nodes.rug.geometry} material={materials['Material.033']} position={[-0.88, 0.57, 0.98]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.09} castShadow receiveShadow/>
        <group name="room" position={[-0.01, 0.57, 0.11]} rotation={[0, Math.PI / 4, 0]} scale={2.35}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.028']} castShadow receiveShadow/>
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['Material.027']} castShadow receiveShadow/>
          <mesh name="Plane010_2" geometry={nodes.Plane010_2.geometry} material={materials['Material.038']} castShadow receiveShadow/>
        </group>
        <group name="desk" position={[1.94, 1.26, -0.39]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.022']} castShadow receiveShadow/>
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} castShadow receiveShadow/>
        </group>
        <group name="monitor" position={[2.46, 1.58, -0.47]} rotation={[Math.PI, -0.49, Math.PI]} scale={0.59}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Material.021']} castShadow receiveShadow/>
        </group>
        <group name="monitor_1" position={[2.02, 1.58, -0.91]} rotation={[Math.PI, -1.08, Math.PI]} scale={0.59}>
          <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane019_1" geometry={nodes.Plane019_1.geometry} material={materials['Material.021']} castShadow receiveShadow/>
        </group>
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials['Material.002']} position={[2.29, 1.35, 0.44]} rotation={[Math.PI, -0.33, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <mesh name="mouse_pad" geometry={nodes.mouse_pad.geometry} material={materials['Material.006']} position={[2.26, 1.35, 0.45]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <group name="speaker" position={[2.89, 1.56, -0.02]} rotation={[Math.PI, -0.13, Math.PI]} scale={0.59}>
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Material.036']} castShadow receiveShadow/>
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        </group>
        <group name="speaker_1" position={[1.58, 1.56, -1.33]} rotation={[Math.PI, -1.3, Math.PI]} scale={0.59}>
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.036']} castShadow receiveShadow/>
          <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        </group>
        <mesh name="v_disk" geometry={nodes.v_disk.geometry} material={materials['Material.001']} position={[1.27, 1.44, -0.86]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <group name="vinyl_player" position={[1.23, 1.35, -0.82]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59}>
          <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Material.027']} castShadow receiveShadow/>
          <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials['Material.025']} castShadow receiveShadow/>
          <mesh name="Plane023_2" geometry={nodes.Plane023_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane023_3" geometry={nodes.Plane023_3.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        </group>
        <group name="board" position={[1.78, 1.35, -0.23]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59}>
          <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['Material.003']} castShadow receiveShadow/>
        </group>
        <group name="audio_panel" position={[1.37, 1.41, -0.64]} rotation={[-Math.PI, -Math.PI / 4, 3.04]} scale={0.59}>
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials['Material.015']} castShadow receiveShadow/>
          <mesh name="Plane012_2" geometry={nodes.Plane012_2.geometry} material={materials['Material.016']} castShadow receiveShadow/>
          <mesh name="Plane012_3" geometry={nodes.Plane012_3.geometry} material={materials['Material.017']} castShadow receiveShadow/>
          <mesh name="Plane012_4" geometry={nodes.Plane012_4.geometry} material={materials['Material.013']} castShadow receiveShadow/>
          <mesh name="Plane012_5" geometry={nodes.Plane012_5.geometry} material={materials['Material.018']} castShadow receiveShadow/>
          <mesh name="Plane012_6" geometry={nodes.Plane012_6.geometry} material={materials['Material.019']} castShadow receiveShadow/>
          <mesh name="Plane012_7" geometry={nodes.Plane012_7.geometry} material={materials['Material.010']} castShadow receiveShadow/>
          <mesh name="Plane012_8" geometry={nodes.Plane012_8.geometry} material={materials['Material.020']} castShadow receiveShadow/>
        </group>
        <group name="main_panel" position={[2.14, 1.41, 0.12]} rotation={[-Math.PI, -Math.PI / 4, 3.04]} scale={0.59}>
          <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={materials['Material.017']} castShadow receiveShadow/>
          <mesh name="Plane013_2" geometry={nodes.Plane013_2.geometry} material={materials['Material.013']} castShadow receiveShadow/>
          <mesh name="Plane013_3" geometry={nodes.Plane013_3.geometry} material={materials['Material.014']} castShadow receiveShadow/>
        </group>
        <group name="panel_2" position={[2.06, 1.41, 0.04]} rotation={[-Math.PI, -Math.PI / 4, 3.04]} scale={0.59}>
          <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane014_1" geometry={nodes.Plane014_1.geometry} material={materials['Material.015']} castShadow receiveShadow/>
          <mesh name="Plane014_2" geometry={nodes.Plane014_2.geometry} material={materials['Material.016']} castShadow receiveShadow/>
          <mesh name="Plane014_3" geometry={nodes.Plane014_3.geometry} material={materials['Material.013']} castShadow receiveShadow/>
        </group>
        <group name="button_panel" position={[1.2, 1.39, -0.47]} rotation={[-Math.PI, -Math.PI / 4, 3.04]} scale={0.59}>
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials['Material.023']} castShadow receiveShadow/>
          <mesh name="Plane015_2" geometry={nodes.Plane015_2.geometry} material={materials['Material.016']} castShadow receiveShadow/>
        </group>
        <group name="panel_1" position={[1.95, 1.39, 0.17]} rotation={[-Math.PI, -Math.PI / 4, 3.04]} scale={0.59}>
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane016_1" geometry={nodes.Plane016_1.geometry} material={materials['Material.005']} castShadow receiveShadow/>
          <mesh name="Plane016_2" geometry={nodes.Plane016_2.geometry} material={materials['Material.021']} castShadow receiveShadow/>
          <mesh name="Plane016_3" geometry={nodes.Plane016_3.geometry} material={materials['Material.013']} castShadow receiveShadow/>
        </group>
        <group name="effects_panel" position={[1.7, 1.49, -0.72]} rotation={[Math.PI, -Math.PI / 4, 2.15]} scale={0.59}>
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Material.014']} castShadow receiveShadow/>
        </group>
        <group name="effects_panel001" position={[2.16, 1.49, -0.26]} rotation={[Math.PI, -Math.PI / 4, 2.15]} scale={0.59}>
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Material.014']} castShadow receiveShadow/>
        </group>
        <mesh name="pillow_2" geometry={nodes.pillow_2.geometry} material={materials['Material.012']} position={[-2.4, 0.88, 0.13]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <mesh name="pillow_3" geometry={nodes.pillow_3.geometry} material={materials['Material.012']} position={[-2.06, 1.17, -0.9]} rotation={[-1.59, -0.02, -2.36]} scale={0.59} castShadow receiveShadow/>
        <mesh name="pillow_4" geometry={nodes.pillow_4.geometry} material={materials['Material.012']} position={[-2.75, 1.17, -0.21]} rotation={[-1.59, -0.02, -2.36]} scale={0.59} castShadow receiveShadow/>
        <mesh name="couch" geometry={nodes.couch.geometry} material={materials['Material.011']} position={[-2.1, 0.72, -0.26]} rotation={[0, -Math.PI / 4, 0]} scale={0.59} castShadow receiveShadow/>
        <mesh name="pillow_1" geometry={nodes.pillow_1.geometry} material={materials['Material.012']} position={[-1.71, 0.88, -0.55]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <group name="keyboard" position={[1.5, 1.23, 1.5]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59}>
          <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane031_1" geometry={nodes.Plane031_1.geometry} material={materials['Material.003']} castShadow receiveShadow/>
        </group>
        <mesh name="white_keys" geometry={nodes.white_keys.geometry} material={materials['Material.004']} position={[2.16, 1.28, 0.87]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <group name="control_panel" position={[2.04, 1.34, 1.12]} rotation={[2.23, -0.55, 2.55]} scale={0.59}>
          <mesh name="Plane071" geometry={nodes.Plane071.geometry} material={materials['Material.002']} castShadow receiveShadow/>
          <mesh name="Plane071_1" geometry={nodes.Plane071_1.geometry} material={materials.Material} castShadow receiveShadow/>
          <mesh name="Plane071_2" geometry={nodes.Plane071_2.geometry} material={materials['Material.005']} castShadow receiveShadow/>
        </group>
        <mesh name="black_key" geometry={nodes.black_key.geometry} material={materials['Material.001']} position={[2.17, 1.3, 0.9]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <mesh name="shelve" geometry={nodes.shelve.geometry} material={materials['Material.031']} position={[-0.03, 0.57, -2.28]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <mesh name="book_1" geometry={nodes.book_1.geometry} material={materials['Material.020']} position={[0.1, 1.46, -2.19]} rotation={[0, 0.02, 1.32]} scale={0.59} castShadow receiveShadow/>
        <mesh name="book_2" geometry={nodes.book_2.geometry} material={materials['Material.030']} position={[-0.58, 1.13, -2.18]} rotation={[0, 0.02, 1.63]} scale={0.59} castShadow receiveShadow/>
        <mesh name="book_3" geometry={nodes.book_3.geometry} material={materials['Material.010']} position={[0.01, 1.44, -2.19]} rotation={[0, 0.02, 0.95]} scale={0.59} castShadow receiveShadow/>
        <mesh name="book_4" geometry={nodes.book_4.geometry} material={materials.Material} position={[-0.41, 1.05, -2.18]} rotation={[0, 0.02, 3.14]} scale={0.59} castShadow receiveShadow/>
        <group name="book_5" position={[-0.37, 1.1, -2.18]} rotation={[0, 0.45, 3.14]} scale={0.59}>
          <mesh name="Plane082" geometry={nodes.Plane082.geometry} material={materials['Material.001']} castShadow receiveShadow/>
          <mesh name="Plane082_1" geometry={nodes.Plane082_1.geometry} material={materials['Material.009']} castShadow receiveShadow/>
        </group>
        <group name="book_6" position={[-0.22, 1.38, -2.19]} rotation={[3.08, 1.54, 0.05]} scale={0.59}>
          <mesh name="Plane083" geometry={nodes.Plane083.geometry} material={materials['Material.010']} castShadow receiveShadow/>
          <mesh name="Plane083_1" geometry={nodes.Plane083_1.geometry} material={materials['Material.009']} castShadow receiveShadow/>
        </group>
        <mesh name="book_set" geometry={nodes.book_set.geometry} material={materials['Material.008']} position={[0.6, 1.47, -2.21]} rotation={[0, 0.02, 1.58]} scale={0.59} castShadow receiveShadow/>
        <mesh name="v_disk_set_1" geometry={nodes.v_disk_set_1.geometry} material={materials['Material.006']} position={[0.45, 1.81, -2.22]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <mesh name="v_disk_set_2" geometry={nodes.v_disk_set_2.geometry} material={materials['Material.020']} position={[-0.36, 1.47, -2.21]} rotation={[Math.PI, -0.02, Math.PI]} scale={0.59} castShadow receiveShadow/>
        <group name="control_panel001" position={[0.08, 1.03, -2.14]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.59}>
          <mesh name="Plane085" geometry={nodes.Plane085.geometry} material={materials.Material} castShadow receiveShadow/>
          <mesh name="Plane085_1" geometry={nodes.Plane085_1.geometry} material={materials['Material.005']} castShadow receiveShadow/>
          <mesh name="Plane085_2" geometry={nodes.Plane085_2.geometry} material={materials['Material.023']} castShadow receiveShadow/>
          <mesh name="Plane085_3" geometry={nodes.Plane085_3.geometry} material={materials['Material.006']} castShadow receiveShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/record_room-transformed.glb')
