/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 person_model.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/person_model.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log('actions', actions)
    actions.idle.play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="body" geometry={nodes.body.geometry} material={materials.skin} skeleton={nodes.body.skeleton} />
          <skinnedMesh name="ears" geometry={nodes.ears.geometry} material={materials.skin} skeleton={nodes.ears.skeleton} />
          <skinnedMesh name="eyes" geometry={nodes.eyes.geometry} material={materials.black} skeleton={nodes.eyes.skeleton} />
          <skinnedMesh name="hair" geometry={nodes.hair.geometry} material={materials.black} skeleton={nodes.hair.skeleton} />
          <skinnedMesh name="head" geometry={nodes.head.geometry} material={materials.skin} skeleton={nodes.head.skeleton} />
          <skinnedMesh name="pants" geometry={nodes.pants.geometry} material={materials.pants} skeleton={nodes.pants.skeleton} />
          <group name="shirt">
            <skinnedMesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.shirt_df} skeleton={nodes.Cube006.skeleton} />
            <skinnedMesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.dark_blue} skeleton={nodes.Cube006_1.skeleton} />
            <skinnedMesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials['Material.001']} skeleton={nodes.Cube006_2.skeleton} />
            <skinnedMesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials['Material.002']} skeleton={nodes.Cube006_3.skeleton} />
          </group>
          <skinnedMesh name="shoes" geometry={nodes.shoes.geometry} material={materials.black} skeleton={nodes.shoes.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/person_model.glb')
